[package]
name = "rustc_codegen_c"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]

# This package uses rustc crates.
[package.metadata.rust-analyzer]
rustc_private=true
