[package]
name = "rustc_codegen_c_ast"
edition = "2021"
version.workspace = true

[dependencies]
bitflags = "2.6.0"

# This package uses rustc crates.
[package.metadata.rust-analyzer]
rustc_private = true
